# Generated by Django 4.2.4 on 2023-09-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.TextField(max_length=5),
        ),
    ]
